services:
  database:
    image: mysql
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: travel
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql
      - ./sqlinit:/docker-entrypoint-initdb.d
